Maintenance
helldivers-2/api pull request #114
Opened 2024-11-10 13:50 UTC by dealloc

Pretty big PR that addresses some of the pending issues:
- update dependencies for security patches etc
- significantly improve DX and compilation times by switching `ISourceGenerator` to `IIncrementalGenerator` which speeds up the source generation from the JSON files to C# files
- speaking of which, updated the [helldivers-2/json](https://github.com/helldivers-2/json) submodule
- add multiple rewards (#109)
- make X-Super-Client headers required (#94) also updates relevant documentation to disable on self host

I'm hoping that updating the json files also addresses #105 but that remains to be seen

2024-11-10 13:57 UTC, lambstream requested changes

2024-11-10 13:57 UTC, lambstream commented on src/Helldivers-2-SourceGen/Helldivers-2-SourceGen.csproj
> +<!--        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0"/>-->
It seems like this could just be removed?

2024-11-10 14:00 UTC, lambstream approved these changes

2024-11-12 04:28 UTC, chatterchats approved these changes
Looks good to me!

2024-11-12 04:32 UTC, merged